version: '3.4'

services:
  zipkin-server:
    image: openzipkin/zipkin:2.23.2
    ports:
      - 9411:9411
    restart: always
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    networks:
      - detoni-network

  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - detoni-network

  naming-server:
    image: scarenci/naming-server
    build:
      context: .
      dockerfile: naming-server/Dockerfile
    ports:
      - 8761:8761
    networks:
      - detoni-network

  api-gateway:
    image: scarenci/api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - 8765:8765
    depends_on:
      - naming-server
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURIO: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - detoni-network

  catalog-microservice:
    image: scarenci/catalog-microservice
    restart: always
    build:
      context: .
      dockerfile: catalog-microservice/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8090:8090
    depends_on:
      - naming-server
      - rabbit-mq
    networks:
      - detoni-network
      
  shopping-microservice:
    image: scarenci/shopping-microservice
    restart: always
    build:
      context: .
      dockerfile: shopping-microservice/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    ports:
      - 8080:8080
    depends_on:
      - naming-server
      - rabbit-mq
    networks:
      - detoni-network
      
networks:
  detoni-network:
    driver: bridge