spring:
  application:
    name: shopping-microservice
  datasource:
    url: jdbc:h2:mem:cart
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
  jackson:
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false 
    spring.h2.console.settings.web-allow-others: false  
  flyway:
    url: jdbc:h2:mem:cart
    user: sa
    password: password
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
shopping-microservice:
  greeting: "Prod"
  default-value: "World"