server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: shopping-microservice
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.64.2:9411/
    
springdoc:
  show-actuator: true
  api-docs:
    path: /shopping-microservice/v3/api-docs 
    
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'